# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: VitaminDev
subtitle: code supplements for “healthy” development
author: Ioannis Nikopoulos
email: ioannis.nikop@gmail.com
author-desc: Software Engineer & Application Development Analyst, capable to deliver high quality applications on time and on budget.
copyright-date: 2017

# url: "http://www.vitamindev.com/"
# baseurl: "" # the subpath of your site, e.g. /blog

# Comments
disqus:
  shortname: vitamindev

# Images
image-path: /assets/img
author-image: author_profile_photo.png
about-me-image: about_me_photo.png

# Social Links
social_links:
  facebook:     "https://www.facebook.com/ioannis.nikopoulos.3"
  google-plus:  "https://plus.google.com/u/0/106093693797217007178"
  linkedin:     "https://www.linkedin.com/in/ioannisnikopoulos/"
  github:       "https://github.com/Ioannis-Nikop"

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  cache: false
  style: compressed
assets:
  cache: false

paginate: 4
